version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1696384672
layout:
  /navigation/:
    -
      - system-messages-7972
    -
      - 'logo-9608 15'
      - 'menu-6409 65'
      - 'social-3171 20'
  /header/:
    -
      - position-position-5243
  /intro/: {  }
  /features/: {  }
  /utility/: {  }
  /above/: {  }
  /testimonials/: {  }
  /expanded/: {  }
  /container-main/:
    -
      -
        'aside 25':
          -
            - position-position-4734
      -
        'mainbar 50':
          -
            - system-content-1587
      -
        'sidebar 25':
          -
            - position-position-3949
  /footer/:
    -
      - 'logo-9571 10'
      - 'copyright-1736 30'
      - 'horizontalmenu-9034 45'
      - 'totop-8670 15'
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  aside:
    attributes:
      class: ''
    block:
      fixed: '1'
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
    block:
      fixed: '1'
  container-main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://LogoNails-violeta.svg'
      link: '0'
      svg: ''
  social-3171:
    attributes:
      css:
        class: ''
      display: icons_only
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: 'fa fa-pinterest'
          text: Pinterest
          title: Pinterest
          link: 'https://ar.pinterest.com/'
          name: Pinterest
    block:
      class: g-social-header
  position-position-5243:
    title: 'Module Position'
    attributes:
      key: module-position
  position-position-4734:
    title: Aside
    attributes:
      key: aside
  position-position-3949:
    title: Sidebar
    attributes:
      key: sidebar
  logo-9571:
    title: 'Logo / Image'
    attributes:
      image: 'gantry-media://LogoNails-violeta.svg'
  copyright-1736:
    attributes:
      date:
        start: '2023'
      owner: Marti2
      additional:
        text: 'Trabajo Practico para Framworks'
  horizontalmenu-9034:
    title: 'Horizontal Menu'
    attributes:
      items: {  }
  totop-8670:
    title: 'To Top'
